# browser is the shell (/bin/sh) command executed once the proxy starts.
# When browser exits, the proxy exits. An extra env var PROXY is available.
#
# Here, we use a separate Chrome instance in Incognito mode, so that
# it can run (and be waited for) alongside the default one, and that
# it maintains no state across runs. To configure this browser open a
# normal window in it, settings will be preserved.
browser = """
    google-chrome-stable \
    --user-data-dir="$HOME/.config/google-chrome-captive" \
    --proxy-server="socks5://$PROXY" \
    --no-first-run \
    --new-window \
    --incognito \
    http://neverssl.com
"""

# dhcp-dns is the shell (/bin/sh) command executed to obtain the DHCP
# DNS server address. The first match of an IPv4 regex is used.
# IPv4 only, because let's be real, it's a captive portal.
#
# `wlan0` is your network interface (wlan0, eth0, ...)
#
# To install the systemd-networkd-dns command, run:
#
#  $ go install github.com/cyb3rko/captive-browser/cmd/systemd-networkd-dns@latest
#
dhcp-dns = "$(go env GOPATH)/bin/systemd-networkd-dns wlan0"

# socks5-addr is the listen address for the SOCKS5 proxy server.
socks5-addr = "localhost:1666"

# bind-device is the interface over which outbound connections (both HTTP
# and DNS) will be established. It can be used to avoid address space collisions
# but it requires CAP_NET_RAW or root privileges. Disabled by default.
#bind-device = "wlan0"
